#!/bin/bash
# This filter avoids submitting tokens to the git repo. To use this:
#
# 1. Create a file ~/.cvp_svc_account.token with CV service account token
# 2. Add the following lines to your .git/config:
#
# [filter "remove-tokens"]
#   clean  = .gitfilters/remove-tokens-clean
#   smudge = .gitfilters/remove-tokens-smudge

set -e
echo "the remote-tokens-clean script is running" > filter.log
sed 's/\(token:\) .*/\1 "PLACE_YOUR_CVP_SVC_ACCOUNT_TOKEN_HERE"/g'
